add display soc button
Merck/forestly pull request #51
Opened 2024-05-13 20:28 UTC by wangben718

This PR try to add a button to show SOC column or hide it

2024-05-13 20:49 UTC, LittleBeannie approved these changes

2024-05-13 21:42 UTC, elong0527 commented
Please add an example in `vignettes` to illustrate the example and output.

2024-05-13 22:26 UTC, nanxstats requested changes

2024-05-13 22:26 UTC, nanxstats commented on R/format_ae_forestly.R
> +      show = F
Prefer `TRUE` and `FALSE` over `T` and `F`. https://style.tidyverse.org/syntax.html#logical-vectors

2024-05-13 22:26 UTC, nanxstats commented on R/format_ae_forestly.R
> +  }
This for-loop should be vectorized to avoid growing the vector sequentially.

2024-05-13 22:26 UTC, nanxstats commented on R/format_ae_forestly.R
> +  # hidden_item <-  paste0("'", hidden_item, "'", collapse = ", ")
Remove commented code

2024-05-20 01:33 UTC, fukuhiro2023 commented
I have updated as below:

- Add argument `display_soc_toggle` in `ae_forestly()` to control the display of SOC toggle button.
- Fix formatting and vectorize the `for` loop based on the comments.
- Enable to show and hide the SOC column with a single button.

2024-05-20 01:56 UTC, nanxstats approved these changes

2024-05-20 01:56 UTC, merged