Display AE in1 page
Merck/forestly pull request #52
Opened 2024-05-17 15:43 UTC by shgeng1216

Add max_page argument to control the max page number showed in the interactive forest table

2024-05-17 18:54 UTC, LittleBeannie reviewed
Thank you so much, @shgeng1216! I understand it is not easy to get all the CMD check pass, and we appreciate your time overcoming all challenging. I only have 1 minor comment below.

2024-05-27 23:35 UTC, nanxstats commented
Is there a particular reason you want to limit customizing the page size options to only the maximum number instead of an arbitrary vector of numbers, like how [reactable](https://glin.github.io/reactable/articles/examples.html#page-size-options) originally supports it?

2024-05-27 23:38 UTC, nanxstats requested changes

2024-05-27 23:38 UTC, nanxstats commented on R/ae_forestly.R
> +#' @param max_page A numeric value of max page number showed in table.
shown, not showed

2024-05-27 23:38 UTC, nanxstats commented on vignettes/layout.Rmd
> +# Maximum Page Options
I'd use sentence case for headings to be consistent with existing headings.

2024-05-27 23:38 UTC, nanxstats commented on vignettes/layout.Rmd
> +It can be adjusted by adding "max_page =xx" argument to ae_forestly() function.
I would simply say:

```
It can be adjusted by using the `max_page` argument in `ae_forestly()`.
```

2024-05-28 13:20 UTC, LittleBeannie commented
> Is there a particular reason you want to limit customizing the page size options to only the maximum number instead of an arbitrary vector of numbers, like how [reactable](https://glin.github.io/reactable/articles/examples.html#page-size-options) originally supports it?

Hi @nanxstats , it is a comment from Lisa.

2024-05-30 01:32 UTC, nanxstats approved these changes

2024-05-30 01:37 UTC, merged

2024-05-30 01:38 UTC, nanxstats commented
OK! It looks like you have strong reasons to make this change, which I fully understand. So let's get it merged. Thanks again for adding this new feature.

2024-05-30 01:47 UTC, shgeng1216 commented
> Is there a particular reason you want to limit customizing the page size options to only the maximum number instead of an arbitrary vector of numbers, like how [reactable](https://glin.github.io/reactable/articles/examples.html#page-size-options) originally supports it?

Hi @nanxstats, thanks for your comments.

Just as Yujie's comment, Lisa proposed this approach, so my initial task is to set a maximum number.  After checking Reactable package, whose default setting is (10, 25, 50, 100). Therefore, we are moving forward with the plan to add a rounded hundred to PageSizeOptions argument if obs larger than 100. But I am always happy to discuss other options you think is more suitable for this case. 

Please feel free to reach out if you have any concerns.

Thanks,
Shuo